### ISSUE TITLE
Warning at server start Minecraft 1.20.4

### ISSUE THREAD

**Issue by RaptorXilef** [coltonj96/UberEnchant#4]
There is currently a BUG.
Every time our Minecraft server is restarted, UberEnchant issues a warning in the console.

```java
[23:00:08 WARN]: [UberEnchant] Task #198 for UberEnchant v8.11.4 generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at me.sciguymjm.uberenchant.UberEnchant.test(UberEnchant.java:104) ~[UberEnchant.jar:?]
	at me.sciguymjm.uberenchant.UberEnchant$1$1.run(UberEnchant.java:94) ~[UberEnchant.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-474]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-474]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1646) ~[paper-1.20.4.jar:git-Paper-474]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-474]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-474]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-474]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-474]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Apart from that, I couldn't find any major problems.

**Serverversion:**
`/version`
```java
This server is running Paper version git-Paper-474 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 3d31e45)
```
`UberEnchant`
```java
UberEnchant 8.11.4
```

I really hope that you can fix this BUG before the next update of the plugin.

With best regards
RaptorXilef

**Comment by coltonj96** [comment]
> There is currently a BUG.
> Every time our Minecraft server is restarted, UberEnchant issues a warning in the console.
> 
> ```java
> [23:00:08 WARN]: [UberEnchant] Task #198 for UberEnchant v8.11.4 generated an exception
> java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
> 	at me.sciguymjm.uberenchant.UberEnchant.test(UberEnchant.java:104) ~[UberEnchant.jar:?]
> 	at me.sciguymjm.uberenchant.UberEnchant$1$1.run(UberEnchant.java:94) ~[UberEnchant.jar:?]
> 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-474]
> 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-474]
> 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1646) ~[paper-1.20.4.jar:git-Paper-474]
> 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-474]
> 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-474]
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-474]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-474]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> ```
> 
> Apart from that, I couldn't find any major problems.
> 
> **Serverversion:**
> `/version`
> ```java
> This server is running Paper version git-Paper-474 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 3d31e45)
> ```
> `UberEnchant`
> ```java
> UberEnchant 8.11.4
> ```
> 
> I really hope that you can fix this BUG before the next update of the plugin.
> 
> With best regards
> RaptorXilef

That error can be ignored at this time. It's a test case I forgot to remove before uploading. It'll be fixed with the next update.

**Comment by RaptorXilef** [comment]
Thank you very much for your answer! I'm glad to hear that, then I can continue to use the really well-made plugin without any concerns until then. Thank you 😊👍
